{{- $object := .Values -}}
{{- if $object.enabled }}
  {{- $_ := set $object "version" .Values.global.version -}}
  {{- if not $object.namespace -}}
    {{- $_ := set $object "namespace" .Values.global.namespace -}}
  {{- end }}


  {{/* Add Service if they are required */}} 
  {{- template "mychart.service" $object }}

  {{/* Add Statefulset if they are required */}}
  {{- template "mychart.statefulset" $object }}

  {{/* Add PersistentVolumeClaims if they are required */}}
  {{- template "mychart.persistent_volume_claim" $object }}

  {{/* Add PersistentVolumes if they are required */}}
  {{- template "mychart.persistent_volume" $object }}
{{- end }}
