# # ------------------------------------------------------------------------------
# # Postgres :
# # ------------------------------------------------------------------------------
postgres:
  enabled: false
  serviceName: postgres
  name: postgres
  image: timescale/timescaledb-ha:pg16   # postgres:16.0
  imagePullPolicy: IfNotPresent
  replicas: 1
  env:
    - name: POSTGRES_PASSWORD
      value: "postgres"
  service_type: ClusterIP
  service:
    - protocol: TCP
      targetPort: 5432
      port: 5432
  securityContext:
    runAsUser: 0  # Run as root user to user persistent volume
    runAsGroup: 0
    fsGroup: 0    
  persistentVolume:
    enabled: true
    volumes:
    - name: postgresql-data
      accessModes: ["ReadWriteOnce"]
      storage: 10Gi
      # mountPath: /home/postgres
      # persistentVolumeReclaimPolicy: Retain
      # storageClassName: local-path                                    # **ONLY FOR TESTING!  NOT FOR PRODUCTION!**
      # # To use a windows path : /run/desktop/mnt/host/c/PATH/TO/FILE
      # # hostPath: /run/desktop/mnt/c/k8/local-storage/postgres_data   # **ONLY FOR TESTING!  NOT FOR PRODUCTION!**
      # hostPath: /mnt/c/k8/local-storage/postgres_data                 # **ONLY FOR TESTING!  NOT FOR PRODUCTION!** # Working version for windows
