# # -----------------------------------------------------------
# # Postgresql : 
# # -----------------------------------------------------------
enabled: true
serviceName: postgres
name: postgres
# Use the timescaledb, since includes ai extension, since rke2 blocks a lot of the apt-get stuff
image: timescale/timescaledb-ha:pg16   # postgres:16.0
imagePullPolicy: IfNotPresent
replicas: 1
labels:
  image: "postgres_version_16_0"
env:
  - name: POSTGRES_PASSWORD
    value: "postgres"
service_type: ClusterIP
service:
  - protocol: TCP
    targetPort: 5432
    port: 5432
securityContext:
  runAsUser: 0  # Run as root user to user persistent volume
  runAsGroup: 0
  fsGroup: 0    
# persistentVolume:
#   enabled: true
#   volumes:
#   - name: postgresql-data
#     accessModes: ["ReadWriteOnce"]
#     storage: 10Gi
#     mountPath: /home/postgres
#     persistentVolumeReclaimPolicy: Retain
#     storageClassName: local-path                                    # **ONLY FOR TESTING!  NOT FOR PRODUCTION!**
#     # To use a windows path : /run/desktop/mnt/host/c/PATH/TO/FILE
#     # hostPath: /run/desktop/mnt/c/k8/local-storage/postgres_data   # **ONLY FOR TESTING!  NOT FOR PRODUCTION!**
#     hostPath: /mnt/c/k8/local-storage/postgres_data                 # **ONLY FOR TESTING!  NOT FOR PRODUCTION!** # Working version for windows
