# ------------------------------------------------------------------------------
# Ollama :
# ------------------------------------------------------------------------------
service: true
serviceName: ollama
name: ollama
image: ollama/ollama:0.12.11
imagePullPolicy: IfNotPresent
replicas: 1
env:
  - name: OLLAMA_HOST
    value: "0.0.0.0:11434" # Expose Ollama on all interfaces within the pod
  - name: PRELOAD_MODELS
    value: "mistral:7b"
  - name: OLLAMA_KEEP_ALIVE 
    value: "12h"
service_type: ClusterIP
service:
  - protocol: TCP
    port: 11434
    targetPort: 11434





# service: true
# serviceName: pgadmin
# name: pgadmin
# image: dpage/pgadmin4:7.8
# imagePullPolicy: IfNotPresent
# replicas: 1
# env:
#   - name: PGADMIN_DEFAULT_EMAIL
#     value: "admin@email.com"
#   - name: PGADMIN_DEFAULT_PASSWORD
#     value: "admin"
# service_type: NodePort
# service:
#   - protocol: TCP
#     port: 80
#     targetPort: 80
#     nodePort: 30010

# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: ollama
#   namespace: {{ $object.namespace }}
#   labels:
#     app: ollama
# spec:
#   # serviceName: "ollama-service"
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ollama
#   template:
#     metadata:
#       labels:
#         app: ollama
#     spec:
#       containers:
#       - name: ollama
#         image: ollama/ollama:0.12.11
#         ports:
#         - containerPort: 11434
#           protocol: TCP
#           name: http
#         # volumeMounts:
#         # - name: ollama-data
#         #   mountPath: /root/.ollama # Or /home/ollama/.ollama depending on the image
#         env:
#         - name: OLLAMA_HOST
#           value: "0.0.0.0:11434" # Expose Ollama on all interfaces within the pod
# #         # Uncomment and configure resource requests/limits if needed
#         resources:
#           requests:
#             memory: "4Gi"
#             cpu: "2000m"
#           limits:
#             memory: "8Gi"
#             cpu: "4000m"
#   volumeClaimTemplates:
#   - metadata:
#       name: ollama-data
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       resources:
#         requests:
#           storage: 50Gi # Adjust storage size as needed for models
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ollama-pvc
#   namespace: ollama
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi # Adjust size as needed for your models