apiVersion: v2
name: mcp-example
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

maintainers:
- name: github.com/cstone157

# dependencies:
##   The airflow helm chart doesn't support overriding the namespace, so I'm excluding it from the depencies
## for the time being.  The Bitnami airflow does support it, but it's secured for the time being, so I'm gonna
## ignore it for now.  The Airflow will have to be manually deployed.
#   - name: airflow
#     version: 8.9.0
#     # repository: https://airflow-helm.github.io/charts
#     repository: oci://registry-1.docker.io/bitnamicharts/airflow
#     alias: airflow
#     namespace: mcp-example