# # ------------------------------------------------------------------------------
# # General informations:
# # ------------------------------------------------------------------------------
global:
  namespace: mcp-example
  version: "0.1a"
  replicaCount: 1

postgres:
  enabled: true
  image: mcp-postgres:v0.1
pgadmin:
  enabled: false
nifi:
  enabled: false

ollama:
  enabled: true
webui:
  enabled: true

env:
  - name: POSTGRES_USER
    value: "postgres"
  - name: POSTGRES_PASSWORD
    value: "postgres"
  - name: POSTGRES_HOST
    value: "postgres"
  - name: POSTGRES_PORT
    value: "5432"
