# # ------------------------------------------------------------------------------
# # General informations:
# # ------------------------------------------------------------------------------
global:
  namespace: monitoring
  version: "0.1a"
  replicaCount: 1