{{- $object := .Values -}}
{{- if $object.enabled }}
  {{- $_ := set $object "version" .Values.global.version -}}
  {{- if not $object.namespace -}}
    {{- $_ := set $object "namespace" .Values.global.namespace -}}
  {{- end }}

  ## Generate the Service using the helper function to create our service
  {{- template "mychart.service" $object }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
{{- template "mychart.metadata" $object }}
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /webui
        pathType: Prefix
        backend:
          service:
            name: {{ $object.name }}
            port:
              number: 30000
---
  {{/* Add Statefulset if they are required */}}
  {{- template "mychart.statefulset" $object }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
{{- template "mychart.metadata" $object }}
spec:
  replicas: {{ $object.replicas }}
  selector:
    matchLabels:
      app: {{ $object.name }}
  template:
    metadata:
      labels:
        app: {{ $object.name }}
    spec:
      containers:
      - name: {{ $object.name }}
        image: {{ $object.image }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
#         env:
#         - name: OLLAMA_BASE_URL
#           value: "http://ollama-service.open-webui.svc.cluster.local:11434"
#         tty: true
#        volumeMounts:
#        - name: webui-volume
#          mountPath: /app/backend/data
#      volumes:
#      - name: webui-volume
#        persistentVolumeClaim:
#          claimName: open-webui-pvc
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# {{- template "mychart.metadata" $object }}
# spec:
#   accessModes: ["ReadWriteOnce"]
#   resources:
#     requests:
#       storage: 2Gi
{{- end }}