apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: mcp-example-server
  name: mcp-example-server
  namespace: mcp-example
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: mcp-example-server
