{{- $object := .Values -}}
{{- if $object.enabled }}
  {{- $_ := set $object "version" .Values.global.version -}}
  {{- if not $object.namespace -}}
    {{- $_ := set $object "namespace" .Values.global.namespace -}}
  {{- end }}


  {{/* Add Service if they are required */}} 
  {{- template "mychart.service" $object }}

---
#apiVersion: extensions/v1beta1
apiVersion: networking.k8s.io/v1
kind: Ingress
{{- template "mychart.metadata" $object }}
spec:
  rules:
  - host: nifi
    http:
      paths:
      - path: /nifi
        pathType: Prefix
        backend:
          service:
            name: nifi-service
            port:
              number: 8180
---
# https://hub.docker.com/r/apache/nifi
apiVersion: apps/v1
kind: StatefulSet
{{- template "mychart.metadata" $object }}
spec:
  replicas: {{ $object.replicas }}
  selector:
    matchLabels:
      app: {{ $object.name }}
  serviceName: {{ $object.name }}
  template:
    metadata:
      labels:
        app: {{ $object.name }}
    spec:
      containers:
        - name: {{ $object.name }}
          image: {{ $object.image }}
          imagePullPolicy: {{ $object.imagePullPolicy }}
          resources:
            requests:
              cpu: "2000m"
              memory: "2Gi"
            limits:
              cpu: "4000m"
              memory: "4Gi"
              nvidia.com/gpu: "0"
          ports:
          - containerPort: 31000
            name: http-port
          - containerPort: 31001
            name: https-port
          - containerPort: 31011
            name: tcp-port1
          - containerPort: 31012
            name: tcp-port2
          - containerPort: 31013
            name: tcp-port3
          - containerPort: 31014
            name: tcp-port4
          - containerPort: 31021
            name: udp-port1
          - containerPort: 31022
            name: udp-port2
          - containerPort: 31023
            name: udp-port3
          - containerPort: 31024
            name: udp-port4
          env:
          {{- range $object.env }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
          {{- end }}
          # volumeMounts:
          # - name: nifi-logs-pv
          #   mountPath: /opt/nifi/nifi-current/logs
          # - name: nifi-content-pv
          #   mountPath: /opt/nifi/nifi-current/content-repository
          # - name: nifi-flowfile-pv
          #   mountPath: /opt/nifi/nifi-current/flowfile-repository
          # - name: nifi-db-pv
          #   mountPath: /opt/nifi/nifi-current/database-repository
          # - name: nifi-provenance-pv
          #   mountPath: /opt/nifi/nifi-current/provenance-repository
        # volumes:
        # - name: nifi-logs-pv
        #   persistentVolumeClaim:
        #    claimName: nifi-logs-pvc
        # - name: nifi-content-pv
        #   persistentVolumeClaim:
        #    claimName: nifi-content-pvc
        # - name: nifi-flowfile-pv
        #   persistentVolumeClaim:
        #     claimName: nifi-flowfile-pvc
        # - name: nifi-db-pv
        #   persistentVolumeClaim:
        #     claimName: nifi-db-pvc
        # - name: nifi-provenance-pv
        #   persistentVolumeClaim:
        #     claimName: nifi-provenance-pvc

{{- /* Add PersistentVolumeClaim if they are required */}}
{{- /* range $object.pvc */}}
{{/*
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- template "mychart.labels" $object }}
  name: {{ .name }}
  namespace: {{ $object.namespace }}
spec:
  accessModes: {{ .accessModes }}
  resources:
    requests:
      storage: {{ .storage }}
*/}}

{{- end }}
