apiVersion: v1
description: Helm chart for deploying the various components that are necissary for developing this (but already exist in the production enviroment).
name: image-registry
version: 0.01.1
appVersion: 0.01.1
keywords:
- dev
