# ------------------------------------------------------------------------------
# PgAdmin :
# ------------------------------------------------------------------------------
enabled: false
service: true
serviceName: pgadmin
name: pgadmin
image: dpage/pgadmin4:7.8
imagePullPolicy: IfNotPresent
replicas: 1
env:
  - name: PGADMIN_DEFAULT_EMAIL
    value: "admin@email.com"
  - name: PGADMIN_DEFAULT_PASSWORD
    value: "admin"
service_type: NodePort
service:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30010
